// Package k3s owns K3s installation, configuration, ownership, and status
// for the appliance: rendering the release-owned config file and systemd
// unit, deciding whether an existing K3s on the host may be reused, and
// interpreting its health. See "K3s Ownership" in docs/release-plan.md.
package k3s

import (
	"errors"
	"fmt"
	"strings"
)

// DefaultClusterCIDR is the appliance-owned pod network. It intentionally
// avoids 10.42.0.0/16 (upstream K3s default) so that range stays free for the
// fixed management WiFi AP (10.42.0.1/24) without breaking Flannel/CNI.
const DefaultClusterCIDR = "10.44.0.0/16"

// DefaultServiceCIDR matches upstream K3s defaults for ClusterIP services.
const DefaultServiceCIDR = "10.43.0.0/16"

// NodeMode determines whether this host owns the K3s control plane or joins
// one that has already been explicitly bootstrapped. Fresh appliance installs
// remain servers; agent mode is a foundation for the later trusted join flow.
type NodeMode string

const (
	NodeModeServer NodeMode = "server"
	NodeModeAgent  NodeMode = "agent"
)

// Config is the appliance-owned K3s configuration. It is always written
// as a file (never passed via environment variables), per "K3s
// configuration is written as files rather than relying on transient
// installer environment variables."
type Config struct {
	Mode     NodeMode
	NodeName string
	DataDir  string
	TLSSANs  []string
	// ServerURL and TokenFile are agent-only. TokenFile avoids putting a join
	// credential in a unit argument or state receipt.
	ServerURL string
	TokenFile string
	// ClusterCIDR overrides the pod CIDR; empty uses DefaultClusterCIDR.
	ClusterCIDR string
	// ServiceCIDR overrides the service CIDR; empty uses DefaultServiceCIDR.
	ServiceCIDR string
}

func (c Config) EffectiveMode() NodeMode {
	if c.Mode == "" {
		return NodeModeServer
	}
	return c.Mode
}

func (c Config) Validate() error {
	if strings.TrimSpace(c.NodeName) == "" {
		return errors.New("k3s config: node name is required")
	}
	if strings.TrimSpace(c.DataDir) == "" {
		return errors.New("k3s config: data dir is required")
	}
	switch c.EffectiveMode() {
	case NodeModeServer:
		return nil
	case NodeModeAgent:
		if strings.TrimSpace(c.ServerURL) == "" {
			return errors.New("k3s config: agent server URL is required")
		}
		if strings.TrimSpace(c.TokenFile) == "" {
			return errors.New("k3s config: agent token file is required")
		}
		return nil
	default:
		return fmt.Errorf("k3s config: unsupported node mode %q", c.Mode)
	}
}

// Render produces the config.yaml content for /etc/rancher/k3s/config.yaml.
// This is the initial v1 baseline field set; product-specific tuning
// arrives once appliance-code's configuration schema pins additional
// values (see Repository Boundary in the plan).
//
// ClusterCIDR/ServiceCIDR are written only when non-empty. Fresh install
// always passes DefaultClusterCIDR / DefaultServiceCIDR. Upgrade omits them
// so an existing cluster retains its on-disk network parameters.
func (c Config) Render() string {
	var b strings.Builder
	b.WriteString("# Generated by appliance install; do not edit by hand.\n")
	// 10.42.0.0/24 is reserved for the management WiFi AP; do not use the
	// upstream K3s default cluster-cidr of 10.42.0.0/16 on fresh installs.
	if cidr := strings.TrimSpace(c.ClusterCIDR); cidr != "" {
		fmt.Fprintf(&b, "cluster-cidr: %q\n", cidr)
	}
	if cidr := strings.TrimSpace(c.ServiceCIDR); cidr != "" {
		fmt.Fprintf(&b, "service-cidr: %q\n", cidr)
	}
	fmt.Fprintf(&b, "node-name: %q\n", c.NodeName)
	fmt.Fprintf(&b, "data-dir: %q\n", c.DataDir)
	b.WriteString("write-kubeconfig-mode: \"0640\"\n")
	if c.EffectiveMode() == NodeModeAgent {
		fmt.Fprintf(&b, "server: %q\n", c.ServerURL)
		fmt.Fprintf(&b, "token-file: %q\n", c.TokenFile)
	}

	if len(c.TLSSANs) > 0 {
		b.WriteString("tls-san:\n")
		for _, san := range c.TLSSANs {
			fmt.Fprintf(&b, "  - %q\n", san)
		}
	}

	return b.String()
}
