// Package k3s owns K3s installation, configuration, ownership, and status
// for the appliance: rendering the release-owned config file and systemd
// unit, deciding whether an existing K3s on the host may be reused, and
// interpreting its health. See "K3s Ownership" in docs/release-plan.md.
package k3s

import (
	"fmt"
	"strings"
)

// DefaultClusterCIDR is the appliance-owned pod network. It intentionally
// avoids 10.42.0.0/16 (upstream K3s default) so that range stays free for the
// fixed management WiFi AP (10.42.0.1/24) without breaking Flannel/CNI.
const DefaultClusterCIDR = "10.44.0.0/16"

// DefaultServiceCIDR matches upstream K3s defaults for ClusterIP services.
const DefaultServiceCIDR = "10.43.0.0/16"

// Config is the appliance-owned K3s configuration. It is always written
// as a file (never passed via environment variables), per "K3s
// configuration is written as files rather than relying on transient
// installer environment variables."
type Config struct {
	NodeName string
	DataDir  string
	TLSSANs  []string
	// ClusterCIDR overrides the pod CIDR; empty uses DefaultClusterCIDR.
	ClusterCIDR string
	// ServiceCIDR overrides the service CIDR; empty uses DefaultServiceCIDR.
	ServiceCIDR string
}

// Render produces the config.yaml content for /etc/rancher/k3s/config.yaml.
// This is the initial v1 baseline field set; product-specific tuning
// arrives once appliance-code's configuration schema pins additional
// values (see Repository Boundary in the plan).
func (c Config) Render() string {
	clusterCIDR := strings.TrimSpace(c.ClusterCIDR)
	if clusterCIDR == "" {
		clusterCIDR = DefaultClusterCIDR
	}
	serviceCIDR := strings.TrimSpace(c.ServiceCIDR)
	if serviceCIDR == "" {
		serviceCIDR = DefaultServiceCIDR
	}

	var b strings.Builder
	b.WriteString("# Generated by appliance install; do not edit by hand.\n")
	// 10.42.0.0/24 is reserved for the management WiFi AP; do not use the
	// upstream K3s default cluster-cidr of 10.42.0.0/16.
	fmt.Fprintf(&b, "cluster-cidr: %q\n", clusterCIDR)
	fmt.Fprintf(&b, "service-cidr: %q\n", serviceCIDR)
	fmt.Fprintf(&b, "node-name: %q\n", c.NodeName)
	fmt.Fprintf(&b, "data-dir: %q\n", c.DataDir)
	b.WriteString("write-kubeconfig-mode: \"0640\"\n")

	if len(c.TLSSANs) > 0 {
		b.WriteString("tls-san:\n")
		for _, san := range c.TLSSANs {
			fmt.Fprintf(&b, "  - %q\n", san)
		}
	}

	return b.String()
}
