package k3s_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/zoncaesaradmin/appliance-ctl/internal/k3s"
)

func TestNormalizeRegistryHost(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"artifact-dns-1.appliance.internal", "artifact-dns-1.appliance.internal"},
		{"https://artifact-dns-1.appliance.internal", "artifact-dns-1.appliance.internal"},
		{"https://artifact-dns-1.appliance.internal/v2/", "artifact-dns-1.appliance.internal"},
		{"artifact-dns-1.appliance.internal/appliance-images", "artifact-dns-1.appliance.internal"},
		{"registry.example:5000", "registry.example:5000"},
	}
	for _, tc := range cases {
		got, err := k3s.NormalizeRegistryHost(tc.in)
		if err != nil {
			t.Fatalf("NormalizeRegistryHost(%q): %v", tc.in, err)
		}
		if got != tc.want {
			t.Fatalf("NormalizeRegistryHost(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestRegistriesConfig_Render(t *testing.T) {
	cfg := k3s.RegistriesConfig{
		Registry:  "artifact-dns-1.appliance.internal",
		Username:  "admin",
		Password:  "s3cret/with:special",
		TLSVerify: false,
	}
	body, err := cfg.Render()
	if err != nil {
		t.Fatal(err)
	}
	s := string(body)
	for _, want := range []string{
		"Generated by appliance install",
		"artifact-dns-1.appliance.internal",
		"https://artifact-dns-1.appliance.internal",
		"username: admin",
		"s3cret/with:special",
		"insecure_skip_verify: true",
	} {
		if !strings.Contains(s, want) {
			t.Fatalf("rendered registries missing %q:\n%s", want, s)
		}
	}
}

func TestRegistriesConfig_Render_TLSVerifyOmitsInsecure(t *testing.T) {
	cfg := k3s.RegistriesConfig{
		Registry:  "registry.example",
		Username:  "u",
		Password:  "p",
		TLSVerify: true,
	}
	body, err := cfg.Render()
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(body), "insecure_skip_verify") {
		t.Fatalf("expected no insecure_skip_verify when TLSVerify=true:\n%s", body)
	}
}

func TestWriteRegistries_Mode0600(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "registries.yaml")
	cfg := k3s.RegistriesConfig{
		Registry:  "registry.example",
		Username:  "u",
		Password:  "p",
		TLSVerify: false,
	}
	if err := k3s.WriteRegistries(path, cfg); err != nil {
		t.Fatal(err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Fatalf("mode = %o, want 0600", info.Mode().Perm())
	}
}

func TestRegistriesConfig_ValidateRequiresAuth(t *testing.T) {
	cfg := k3s.RegistriesConfig{Registry: "reg.example", Username: "u"}
	if err := cfg.Validate(); err == nil {
		t.Fatal("expected error for missing password")
	}
}
