package k3s

import (
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/zoncaesaradmin/appliance-ctl/internal/lifecycle"
	"gopkg.in/yaml.v3"
)

// RegistriesConfig is the optional LAN/image-pull registry that K3s
// containerd may use in addition to offline preload. When configured,
// zonctl writes /etc/rancher/k3s/registries.yaml before (re)starting K3s.
type RegistriesConfig struct {
	// Registry is the registry host (and optional :port), with no scheme
	// or repository path. Example: artifact-dns-1.appliance.internal
	Registry string
	Username string
	Password string
	// TLSVerify is true when containerd must verify the registry TLS
	// certificate. When false, insecure_skip_verify is set in registries.yaml.
	TLSVerify bool
}

// NormalizeRegistryHost strips a scheme and any path, leaving host[:port].
func NormalizeRegistryHost(raw string) (string, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", fmt.Errorf("k3s: registry host is empty")
	}
	if strings.Contains(raw, "://") {
		u, err := url.Parse(raw)
		if err != nil {
			return "", fmt.Errorf("k3s: parse registry host %q: %w", raw, err)
		}
		if u.Host == "" {
			return "", fmt.Errorf("k3s: registry host %q has no host", raw)
		}
		raw = u.Host
	} else {
		// host/repo/name → host
		raw = strings.SplitN(raw, "/", 2)[0]
	}
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", fmt.Errorf("k3s: registry host is empty after normalize")
	}
	return raw, nil
}

// Validate checks required fields after normalization.
func (c *RegistriesConfig) Validate() error {
	host, err := NormalizeRegistryHost(c.Registry)
	if err != nil {
		return err
	}
	c.Registry = host
	if strings.TrimSpace(c.Username) == "" {
		return fmt.Errorf("k3s: image pull registry username is required")
	}
	if strings.TrimSpace(c.Password) == "" {
		return fmt.Errorf("k3s: image pull registry password/token is required")
	}
	return nil
}

// Render produces registries.yaml content for K3s/containerd.
func (c RegistriesConfig) Render() ([]byte, error) {
	cfg := c
	if err := cfg.Validate(); err != nil {
		return nil, err
	}

	type tlsCfg struct {
		InsecureSkipVerify bool `yaml:"insecure_skip_verify,omitempty"`
	}
	type authCfg struct {
		Username string `yaml:"username"`
		Password string `yaml:"password"`
	}
	type hostCfg struct {
		Auth *authCfg `yaml:"auth"`
		TLS  *tlsCfg  `yaml:"tls,omitempty"`
	}
	type mirrorCfg struct {
		Endpoint []string `yaml:"endpoint"`
	}
	doc := struct {
		Mirrors map[string]mirrorCfg `yaml:"mirrors"`
		Configs map[string]hostCfg   `yaml:"configs"`
	}{
		Mirrors: map[string]mirrorCfg{
			cfg.Registry: {Endpoint: []string{"https://" + cfg.Registry}},
		},
		Configs: map[string]hostCfg{
			cfg.Registry: {
				Auth: &authCfg{Username: cfg.Username, Password: cfg.Password},
			},
		},
	}
	if !cfg.TLSVerify {
		host := doc.Configs[cfg.Registry]
		host.TLS = &tlsCfg{InsecureSkipVerify: true}
		doc.Configs[cfg.Registry] = host
	}

	body, err := yaml.Marshal(&doc)
	if err != nil {
		return nil, fmt.Errorf("k3s: marshal registries.yaml: %w", err)
	}
	header := []byte("# Generated by appliance install; do not edit by hand.\n")
	return append(header, body...), nil
}

// WriteRegistries atomically writes cfg to path with mode 0600 (auth present).
func WriteRegistries(path string, cfg RegistriesConfig) error {
	content, err := cfg.Render()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("k3s: create registries directory: %w", err)
	}
	return lifecycle.WriteFileAtomic(path, content, 0o600)
}
